repos:
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
          # Config for black lives in pyproject.toml
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==22.10.0]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
            args: ["--markdown-linebreak-ext=md,markdown"]
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-ast
          - id: fix-byte-order-marker
          - id: check-merge-conflict
          - id: debug-statements
          - id: detect-private-key
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
    - repo: https://github.com/uktrade/pii-secret-check-hooks
      rev: 0.0.0.33
      hooks:
          - id: pii_secret_filename
            files: ''
            language: python
            args: [exclude]
            pass_filenames: true
            require_serial: true
          - id: pii_secret_file_content
            files: ''
            language: python
            args: [--exclude=pii-secret-exclude.txt]
            pass_filenames: true
            require_serial: true
            additional_dependencies: [click==8.0.4]
          #- id: hooks_version_check
          #  name: Checking local hooks against latest release
          #  verbose: true
          #  require_serial: true
